CREATE TABLE IF NOT EXISTS knowledge_subsections (
  id SERIAL PRIMARY KEY,
  subsection_name VARCHAR(255) UNIQUE NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);